# Generated by Django 2.2.1 on 2020-02-13 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20200213_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='example3',
            name='create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='example3',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
